/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomButton {
    }
    interface MiSaludo {
        "edad": number;
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WcSuma {
    }
    interface WcTabla {
        "data": { headers: string[], rows: any[][] };
    }
}
declare global {
    interface HTMLCustomButtonElement extends Components.CustomButton, HTMLStencilElement {
    }
    var HTMLCustomButtonElement: {
        prototype: HTMLCustomButtonElement;
        new (): HTMLCustomButtonElement;
    };
    interface HTMLMiSaludoElement extends Components.MiSaludo, HTMLStencilElement {
    }
    var HTMLMiSaludoElement: {
        prototype: HTMLMiSaludoElement;
        new (): HTMLMiSaludoElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWcSumaElement extends Components.WcSuma, HTMLStencilElement {
    }
    var HTMLWcSumaElement: {
        prototype: HTMLWcSumaElement;
        new (): HTMLWcSumaElement;
    };
    interface HTMLWcTablaElement extends Components.WcTabla, HTMLStencilElement {
    }
    var HTMLWcTablaElement: {
        prototype: HTMLWcTablaElement;
        new (): HTMLWcTablaElement;
    };
    interface HTMLElementTagNameMap {
        "custom-button": HTMLCustomButtonElement;
        "mi-saludo": HTMLMiSaludoElement;
        "my-component": HTMLMyComponentElement;
        "wc-suma": HTMLWcSumaElement;
        "wc-tabla": HTMLWcTablaElement;
    }
}
declare namespace LocalJSX {
    interface CustomButton {
    }
    interface MiSaludo {
        "edad"?: number;
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WcSuma {
    }
    interface WcTabla {
        "data"?: { headers: string[], rows: any[][] };
    }
    interface IntrinsicElements {
        "custom-button": CustomButton;
        "mi-saludo": MiSaludo;
        "my-component": MyComponent;
        "wc-suma": WcSuma;
        "wc-tabla": WcTabla;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-button": LocalJSX.CustomButton & JSXBase.HTMLAttributes<HTMLCustomButtonElement>;
            "mi-saludo": LocalJSX.MiSaludo & JSXBase.HTMLAttributes<HTMLMiSaludoElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wc-suma": LocalJSX.WcSuma & JSXBase.HTMLAttributes<HTMLWcSumaElement>;
            "wc-tabla": LocalJSX.WcTabla & JSXBase.HTMLAttributes<HTMLWcTablaElement>;
        }
    }
}
