version: "3.9"

services:
  java_app:
    container_name: test_soap
    image: nrc16509-api_soap:1.0.0
    build: .
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5433/bd-test
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bd-test