version: "3.9"
services:
  java_app:
    container_name: java_app
    image: nrc16509-api_rest:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5434/bd-test
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bd-test
volumes:
  postgres_data: