/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomCard {
        "description": string;
        "imgSrc": string;
        "titulo": string;
    }
    interface CustomElement {
    }
    interface DataTable {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCustomCardElement extends Components.CustomCard, HTMLStencilElement {
    }
    var HTMLCustomCardElement: {
        prototype: HTMLCustomCardElement;
        new (): HTMLCustomCardElement;
    };
    interface HTMLCustomElementElement extends Components.CustomElement, HTMLStencilElement {
    }
    var HTMLCustomElementElement: {
        prototype: HTMLCustomElementElement;
        new (): HTMLCustomElementElement;
    };
    interface HTMLDataTableElement extends Components.DataTable, HTMLStencilElement {
    }
    var HTMLDataTableElement: {
        prototype: HTMLDataTableElement;
        new (): HTMLDataTableElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "custom-card": HTMLCustomCardElement;
        "custom-element": HTMLCustomElementElement;
        "data-table": HTMLDataTableElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CustomCard {
        "description"?: string;
        "imgSrc"?: string;
        "titulo"?: string;
    }
    interface CustomElement {
    }
    interface DataTable {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "custom-card": CustomCard;
        "custom-element": CustomElement;
        "data-table": DataTable;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-card": LocalJSX.CustomCard & JSXBase.HTMLAttributes<HTMLCustomCardElement>;
            "custom-element": LocalJSX.CustomElement & JSXBase.HTMLAttributes<HTMLCustomElementElement>;
            "data-table": LocalJSX.DataTable & JSXBase.HTMLAttributes<HTMLDataTableElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
